---
- name: OSPF
  hosts: all
  become: true
  vars_files:
    - defaults/main.yml
  tasks:
    - name: Устанавливаем основные пакеты
      apt:
        name:
          - vim
          - traceroute
          - tcpdump
          - net-tools
        state: present
        update_cache: true
    - name: Отключаем UFW
      service:
        name: ufw
        state: stopped
        enabled: false
    - name: Добавляем gpg-key репозитория
      apt_key:
        url: "https://deb.frrouting.org/frr/keys.asc"
        state: present
    - name: Добавляем репозиторий
      apt_repository:
        repo: 'deb https://deb.frrouting.org/frr {{ ansible_distribution_release }} frr-stable'
        state: present
    - name: устанавливаем FRR
      apt:
        name:
          - frr
          - frr-pythontools
        state: present
        update_cache: true
    - name: Включаем маршрутизацию транзитных пакетов
      sysctl:
        name: net.ipv4.conf.all.forwarding
        value: '1'
        state: present
    - name: тключаем запрет ассиметричного роутинга
      sysctl:
        name: net.ipv4.conf.all.rp_filter
        value: '0'
        state: present
    - name: Копируем файл daemons на хосты
      template:
        src: daemons
        dest: /etc/frr/daemons
        owner: frr
        group: frr
        mode: 0640
    - name: Копируем файл frr.conf на хосты
      template:
        src: frr.conf.j2
        dest: /etc/frr/frr.conf
        owner: frr
        group: frr
        mode: 0640
      tags:
        - setup_ospf
    - name: Перезапускам FRR 
      service:
        name: frr
        state: restarted
        enabled: true
      tags:
        - setup_ospf